const countries = [
  {
    label: 'India',
    value: 'IN',
    code: '+91',
    image: require('../../assets/in.png'),
  },
  {
    label: 'Afghanistan',
    value: 'AF',
    code: '+93',
    image: require('../../assets/af.png'),
  },
  {
    label: 'Albania',
    value: 'AL',
    code: '+355',
    image: require('../../assets/al.png'),
  },
  {
    label: 'Algeria',
    value: 'DZ',
    code: '+213',
    image: require('../../assets/dz.png'),
  },
  {
    label: 'Andorra',
    value: 'AD',
    code: '+376',
    image: require('../../assets/ad.png'),
  },
  {
    label: 'Angola',
    value: 'AO',
    code: '+244',
    image: require('../../assets/ao.png'),
  },
  {
    label: 'Argentina',
    value: 'AR',
    code: '+54',
    image: require('../../assets/ar.png'),
  },
  {
    label: 'Armenia',
    value: 'AM',
    code: '+374',
    image: require('../../assets/am.png'),
  },
  {
    label: 'Australia',
    value: 'AU',
    code: '+61',
    image: require('../../assets/au.png'),
  },
  {
    label: 'Austria',
    value: 'AT',
    code: '+43',
    image: require('../../assets/at.png'),
  },
  {
    label: 'Azerbaijan',
    value: 'AZ',
    code: '+994',
    image: require('../../assets/az.png'),
  },
  {
    label: 'Bahrain',
    value: 'BH',
    code: '+973',
    image: require('../../assets/bh.png'),
  },
  {
    label: 'Bangladesh',
    value: 'BD',
    code: '+880',
    image: require('../../assets/bd.png'),
  },
  {
    label: 'Belarus',
    value: 'BY',
    code: '+375',
    image: require('../../assets/by.png'),
  },
  {
    label: 'Belgium',
    value: 'BE',
    code: '+32',
    image: require('../../assets/be.png'),
  },
  {
    label: 'Bhutan',
    value: 'BT',
    code: '+975',
    image: require('../../assets/bt.png'),
  },
  {
    label: 'Bolivia',
    value: 'BO',
    code: '+591',
    image: require('../../assets/bo.png'),
  },
  {
    label: 'Bosnia and Herzegovina',
    value: 'BA',
    code: '+387',
    image: require('../../assets/ba.png'),
  },
  {
    label: 'Botswana',
    value: 'BW',
    code: '+267',
    image: require('../../assets/bw.png'),
  },
  {
    label: 'Brazil',
    value: 'BR',
    code: '+55',
    image: require('../../assets/br.png'),
  },
  {
    label: 'Brunei',
    value: 'BN',
    code: '+673',
    image: require('../../assets/bn.png'),
  },
  {
    label: 'Bulgaria',
    value: 'BG',
    code: '+359',
    image: require('../../assets/bg.png'),
  },
  {
    label: 'Cambodia',
    value: 'KH',
    code: '+855',
    image: require('../../assets/kh.png'),
  },
  {
    label: 'Cameroon',
    value: 'CM',
    code: '+237',
    image: require('../../assets/cm.png'),
  },
  {
    label: 'Canada',
    value: 'CA',
    code: '+1',
    image: require('../../assets/ca.png'),
  },
  {
    label: 'Chile',
    value: 'CL',
    code: '+56',
    image: require('../../assets/cl.png'),
  },
  {
    label: 'China',
    value: 'CN',
    code: '+86',
    image: require('../../assets/cn.png'),
  },
  {
    label: 'Colombia',
    value: 'CO',
    code: '+57',
    image: require('../../assets/co.png'),
  },
  {
    label: 'Congo',
    value: 'CG',
    code: '+242',
    image: require('../../assets/cg.png'),
  },
  {
    label: 'Costa Rica',
    value: 'CR',
    code: '+506',
    image: require('../../assets/cr.png'),
  },
  {
    label: 'Croatia',
    value: 'HR',
    code: '+385',
    image: require('../../assets/hr.png'),
  },
  {
    label: 'Cuba',
    value: 'CU',
    code: '+53',
    image: require('../../assets/cu.png'),
  },
  {
    label: 'Cyprus',
    value: 'CY',
    code: '+357',
    image: require('../../assets/cy.png'),
  },
  {
    label: 'Czech Republic',
    value: 'CZ',
    code: '+420',
    image: require('../../assets/cz.png'),
  },
  {
    label: 'Denmark',
    value: 'DK',
    code: '+45',
    image: require('../../assets/dk.png'),
  },
  {
    label: 'Dominican Republic',
    value: 'DO',
    code: '+1',
    image: require('../../assets/do.png'),
  },
  {
    label: 'Ecuador',
    value: 'EC',
    code: '+593',
    image: require('../../assets/ec.png'),
  },
  {
    label: 'Egypt',
    value: 'EG',
    code: '+20',
    image: require('../../assets/eg.png'),
  },
  {
    label: 'El Salvador',
    value: 'SV',
    code: '+503',
    image: require('../../assets/sv.png'),
  },
  {
    label: 'Estonia',
    value: 'EE',
    code: '+372',
    image: require('../../assets/ee.png'),
  },
  {
    label: 'Ethiopia',
    value: 'ET',
    code: '+251',
    image: require('../../assets/et.png'),
  },
  {
    label: 'Fiji',
    value: 'FJ',
    code: '+679',
    image: require('../../assets/fj.png'),
  },
  {
    label: 'Finland',
    value: 'FI',
    code: '+358',
    image: require('../../assets/fi.png'),
  },
  {
    label: 'France',
    value: 'FR',
    code: '+33',
    image: require('../../assets/fr.png'),
  },
  {
    label: 'Gabon',
    value: 'GA',
    code: '+241',
    image: require('../../assets/ga.png'),
  },
  {
    label: 'Gambia',
    value: 'GM',
    code: '+220',
    image: require('../../assets/gm.png'),
  },
  {
    label: 'Georgia',
    value: 'GE',
    code: '+995',
    image: require('../../assets/ge.png'),
  },
  {
    label: 'Germany',
    value: 'DE',
    code: '+49',
    image: require('../../assets/de.png'),
  },
  {
    label: 'Ghana',
    value: 'GH',
    code: '+233',
    image: require('../../assets/gh.png'),
  },
  {
    label: 'Greece',
    value: 'GR',
    code: '+30',
    image: require('../../assets/gr.png'),
  },
  {
    label: 'Guatemala',
    value: 'GT',
    code: '+502',
    image: require('../../assets/gt.png'),
  },
  {
    label: 'Guinea',
    value: 'GN',
    code: '+224',
    image: require('../../assets/gn.png'),
  },
  {
    label: 'Honduras',
    value: 'HN',
    code: '+504',
    image: require('../../assets/hn.png'),
  },
  {
    label: 'Hong Kong',
    value: 'HK',
    code: '+852',
    image: require('../../assets/hk.png'),
  },
  {
    label: 'Hungary',
    value: 'HU',
    code: '+36',
    image: require('../../assets/hu.png'),
  },
  {
    label: 'Iceland',
    value: 'IS',
    code: '+354',
    image: require('../../assets/is.png'),
  },

  {
    label: 'Indonesia',
    value: 'ID',
    code: '+62',
    image: require('../../assets/id.png'),
  },
  {
    label: 'Iran',
    value: 'IR',
    code: '+98',
    image: require('../../assets/ir.png'),
  },
  {
    label: 'Iraq',
    value: 'IQ',
    code: '+964',
    image: require('../../assets/iq.png'),
  },
  {
    label: 'Ireland',
    value: 'IE',
    code: '+353',
    image: require('../../assets/ie.png'),
  },
  {
    label: 'Israel',
    value: 'IL',
    code: '+972',
    image: require('../../assets/il.png'),
  },
  {
    label: 'Italy',
    value: 'IT',
    code: '+39',
    image: require('../../assets/it.png'),
  },
  {
    label: 'Jamaica',
    value: 'JM',
    code: '+1',
    image: require('../../assets/jm.png'),
  },
  {
    label: 'Japan',
    value: 'JP',
    code: '+81',
    image: require('../../assets/jp.png'),
  },
  {
    label: 'Jordan',
    value: 'JO',
    code: '+962',
    image: require('../../assets/jo.png'),
  },
  {
    label: 'Kazakhstan',
    value: 'KZ',
    code: '+7',
    image: require('../../assets/kz.png'),
  },
  {
    label: 'Kenya',
    value: 'KE',
    code: '+254',
    image: require('../../assets/ke.png'),
  },
  {
    label: 'South Korea',
    value: 'KR',
    code: '+82',
    image: require('../../assets/kr.png'),
  },
  {
    label: 'Kuwait',
    value: 'KW',
    code: '+965',
    image: require('../../assets/kw.png'),
  },
  {
    label: 'Kyrgyzstan',
    value: 'KG',
    code: '+996',
    image: require('../../assets/kg.png'),
  },
  {
    label: 'Laos',
    value: 'LA',
    code: '+856',
    image: require('../../assets/la.png'),
  },
  {
    label: 'Latvia',
    value: 'LV',
    code: '+371',
    image: require('../../assets/lv.png'),
  },
  {
    label: 'Lebanon',
    value: 'LB',
    code: '+961',
    image: require('../../assets/lb.png'),
  },
  {
    label: 'Liberia',
    value: 'LR',
    code: '+231',
    image: require('../../assets/lr.png'),
  },
  {
    label: 'Libya',
    value: 'LY',
    code: '+218',
    image: require('../../assets/ly.png'),
  },
  {
    label: 'Liechtenstein',
    value: 'LI',
    code: '+423',
    image: require('../../assets/li.png'),
  },
  {
    label: 'Lithuania',
    value: 'LT',
    code: '+370',
    image: require('../../assets/lt.png'),
  },
  {
    label: 'Luxembourg',
    value: 'LU',
    code: '+352',
    image: require('../../assets/lu.png'),
  },
  {
    label: 'Madagascar',
    value: 'MG',
    code: '+261',
    image: require('../../assets/mg.png'),
  },
  {
    label: 'Malawi',
    value: 'MW',
    code: '+265',
    image: require('../../assets/mw.png'),
  },
  {
    label: 'Malaysia',
    value: 'MY',
    code: '+60',
    image: require('../../assets/my.png'),
  },
  {
    label: 'Maldives',
    value: 'MV',
    code: '+960',
    image: require('../../assets/mv.png'),
  },
  {
    label: 'Mali',
    value: 'ML',
    code: '+223',
    image: require('../../assets/ml.png'),
  },
  {
    label: 'Malta',
    value: 'MT',
    code: '+356',
    image: require('../../assets/mt.png'),
  },
  {
    label: 'Mauritania',
    value: 'MR',
    code: '+222',
    image: require('../../assets/mr.png'),
  },
  {
    label: 'Mexico',
    value: 'MX',
    code: '+52',
    image: require('../../assets/mx.png'),
  },
  {
    label: 'Moldova',
    value: 'MD',
    code: '+373',
    image: require('../../assets/md.png'),
  },
  {
    label: 'Monaco',
    value: 'MC',
    code: '+377',
    image: require('../../assets/mc.png'),
  },
  {
    label: 'Mongolia',
    value: 'MN',
    code: '+976',
    image: require('../../assets/mn.png'),
  },
  {
    label: 'Montenegro',
    value: 'ME',
    code: '+382',
    image: require('../../assets/me.png'),
  },
  {
    label: 'Morocco',
    value: 'MA',
    code: '+212',
    image: require('../../assets/ma.png'),
  },
  {
    label: 'Mozambique',
    value: 'MZ',
    code: '+258',
    image: require('../../assets/mz.png'),
  },
  {
    label: 'Myanmar',
    value: 'MM',
    code: '+95',
    image: require('../../assets/mm.png'),
  },
  {
    label: 'Namibia',
    value: 'NA',
    code: '+264',
    image: require('../../assets/na.png'),
  },
  {
    label: 'Nepal',
    value: 'NP',
    code: '+977',
    image: require('../../assets/np.png'),
  },
  {
    label: 'Netherlands',
    value: 'NL',
    code: '+31',
    image: require('../../assets/nl.png'),
  },
  {
    label: 'New Zealand',
    value: 'NZ',
    code: '+64',
    image: require('../../assets/nz.png'),
  },
  {
    label: 'Nicaragua',
    value: 'NI',
    code: '+505',
    image: require('../../assets/ni.png'),
  },
  {
    label: 'Niger',
    value: 'NE',
    code: '+227',
    image: require('../../assets/ne.png'),
  },
  {
    label: 'Nigeria',
    value: 'NG',
    code: '+234',
    image: require('../../assets/ng.png'),
  },
  {
    label: 'North Macedonia',
    value: 'MK',
    code: '+389',
    image: require('../../assets/mk.png'),
  },
  {
    label: 'Norway',
    value: 'NO',
    code: '+47',
    image: require('../../assets/no.png'),
  },
  {
    label: 'Oman',
    value: 'OM',
    code: '+968',
    image: require('../../assets/om.png'),
  },
  {
    label: 'Pakistan',
    value: 'PK',
    code: '+92',
    image: require('../../assets/pk.png'),
  },
  {
    label: 'Panama',
    value: 'PA',
    code: '+507',
    image: require('../../assets/pa.png'),
  },
  {
    label: 'Paraguay',
    value: 'PY',
    code: '+595',
    image: require('../../assets/py.png'),
  },
  {
    label: 'Peru',
    value: 'PE',
    code: '+51',
    image: require('../../assets/pe.png'),
  },
  {
    label: 'Philippines',
    value: 'PH',
    code: '+63',
    image: require('../../assets/ph.png'),
  },
  {
    label: 'Poland',
    value: 'PL',
    code: '+48',
    image: require('../../assets/pl.png'),
  },
  {
    label: 'Portugal',
    value: 'PT',
    code: '+351',
    image: require('../../assets/pt.png'),
  },
  {
    label: 'Qatar',
    value: 'QA',
    code: '+974',
    image: require('../../assets/qa.png'),
  },
  {
    label: 'Romania',
    value: 'RO',
    code: '+40',
    image: require('../../assets/ro.png'),
  },
  {
    label: 'Russia',
    value: 'RU',
    code: '+7',
    image: require('../../assets/ru.png'),
  },
  {
    label: 'Rwanda',
    value: 'RW',
    code: '+250',
    image: require('../../assets/rw.png'),
  },
  {
    label: 'Saudi Arabia',
    value: 'SA',
    code: '+966',
    image: require('../../assets/sa.png'),
  },
  {
    label: 'Senegal',
    value: 'SN',
    code: '+221',
    image: require('../../assets/sn.png'),
  },
  {
    label: 'Serbia',
    value: 'RS',
    code: '+381',
    image: require('../../assets/rs.png'),
  },
  {
    label: 'Singapore',
    value: 'SG',
    code: '+65',
    image: require('../../assets/sg.png'),
  },
  {
    label: 'Slovakia',
    value: 'SK',
    code: '+421',
    image: require('../../assets/sk.png'),
  },
  {
    label: 'Slovenia',
    value: 'SI',
    code: '+386',
    image: require('../../assets/si.png'),
  },
  {
    label: 'Somalia',
    value: 'SO',
    code: '+252',
    image: require('../../assets/so.png'),
  },
  {
    label: 'South Africa',
    value: 'ZA',
    code: '+27',
    image: require('../../assets/za.png'),
  },
  {
    label: 'Spain',
    value: 'ES',
    code: '+34',
    image: require('../../assets/es.png'),
  },
  {
    label: 'Sri Lanka',
    value: 'LK',
    code: '+94',
    image: require('../../assets/lk.png'),
  },
  {
    label: 'Sudan',
    value: 'SD',
    code: '+249',
    image: require('../../assets/sd.png'),
  },
  {
    label: 'Sweden',
    value: 'SE',
    code: '+46',
    image: require('../../assets/se.png'),
  },
  {
    label: 'Switzerland',
    value: 'CH',
    code: '+41',
    image: require('../../assets/ch.png'),
  },
  {
    label: 'Syria',
    value: 'SY',
    code: '+963',
    image: require('../../assets/sy.png'),
  },
  {
    label: 'Taiwan',
    value: 'TW',
    code: '+886',
    image: require('../../assets/tw.png'),
  },
  {
    label: 'Tajikistan',
    value: 'TJ',
    code: '+992',
    image: require('../../assets/tj.png'),
  },
  {
    label: 'Tanzania',
    value: 'TZ',
    code: '+255',
    image: require('../../assets/tz.png'),
  },
  {
    label: 'Thailand',
    value: 'TH',
    code: '+66',
    image: require('../../assets/th.png'),
  },
  {
    label: 'Togo',
    value: 'TG',
    code: '+228',
    image: require('../../assets/tg.png'),
  },
  {
    label: 'Tunisia',
    value: 'TN',
    code: '+216',
    image: require('../../assets/tn.png'),
  },
  {
    label: 'Turkey',
    value: 'TR',
    code: '+90',
    image: require('../../assets/tr.png'),
  },
  {
    label: 'Uganda',
    value: 'UG',
    code: '+256',
    image: require('../../assets/ug.png'),
  },
  {
    label: 'Ukraine',
    value: 'UA',
    code: '+380',
    image: require('../../assets/ua.png'),
  },
  {
    label: 'United Arab Emirates',
    value: 'AE',
    code: '+971',
    image: require('../../assets/ae.png'),
  },
  {
    label: 'United Kingdom',
    value: 'GB',
    code: '+44',
    image: require('../../assets/gb.png'),
  },
  {
    label: 'United States',
    value: 'US',
    code: '+1',
    image: require('../../assets/us.png'),
  },
  {
    label: 'Uruguay',
    value: 'UY',
    code: '+598',
    image: require('../../assets/uy.png'),
  },
  {
    label: 'Uzbekistan',
    value: 'UZ',
    code: '+998',
    image: require('../../assets/uz.png'),
  },
  {
    label: 'Venezuela',
    value: 'VE',
    code: '+58',
    image: require('../../assets/ve.png'),
  },
  {
    label: 'Vietnam',
    value: 'VN',
    code: '+84',
    image: require('../../assets/vn.png'),
  },
  {
    label: 'Yemen',
    value: 'YE',
    code: '+967',
    image: require('../../assets/ye.png'),
  },
  {
    label: 'Zambia',
    value: 'ZM',
    code: '+260',
    image: require('../../assets/zm.png'),
  },
  {
    label: 'Zimbabwe',
    value: 'ZW',
    code: '+263',
    image: require('../../assets/zw.png'),
  },
];
export default countries;
